[package]
name = "VoxelCraft"
version = "0.1.0"
authors = [" EternalMC <jamesdrothermel@gmail.com> "]
edition = "2018"

[dependencies]
amethyst = "0.13.2"
rand = "0.7.2"
amethyst_physics = "0.1.1"
amethyst_nphysics = "0.1.1"

[features]
empty = ["amethyst/empty"]
vulkan = ["amethyst/vulkan"]
